[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"


[project]
name = "pydentity-db-sqlalchemy"
version = "1.0.0"
dependencies = [
    "sqlalchemy>=2.0.31"
]

[tool.setuptools.packages.find]
exclude = [
    "tests*",
    "examples*"
]
